### ISSUE TITLE
git open --issue open the main github repo page, no open issues page.

### ISSUE THREAD

**Issue by roboto-cloud** [paulirish/git-open#118]
Hi, this commando don't open the issues page, just go to the main repo page...
tested on github and gitlab

`git open --issue`

someone know how fix it?

Thanks in advance,

**Comment by ffes** [comment]
`--issue` opens the specific page of that issue when you use the special branch name.

What you are looking for is the not yet contributed `--issues`.

**Comment by derimagia** [comment]
Going to close this, let us know if you are still having issues.

Idea: maybe we can fall back to opening the issues page if the user doesn't have a branch name we can parse an issue number out of
