### ISSUE TITLE
Branches named different locally than what is tracked as upstream

### ISSUE THREAD

**Issue by drKnoxy** [paulirish/git-open#124]
When I have `push.default` set to `upstream` I think the upstream branch should be opened.

I can put together a PR if you want to offer some guidance in what you are looking for.

**Comment by derimagia** [comment]
Sorry for the delay, I agree with you on this. If you're still interested in doing a PR - here's the relevant code: 

https://github.com/paulirish/git-open/blob/5fefffede3b8cf1e5363e2180066cf185cc280e1/git-open#L45-L50

**Comment by lovef** [comment]
I believe this relates to the PR I opened: #140, though I disregard `push.default` and always default to upstream branch as that fits my use case.

**Comment by derimagia** [comment]
@lovef fixed this in #140. If you continue to have an issue on master let us know
