### ISSUE TITLE
[feature] Bash-it support 

### ISSUE THREAD

**Issue by NGenetzky** [paulirish/git-open#131]
[Bashit](https://github.com/Bash-it/bash-it) is like oh-my-zsh.

This would be a nice plugin to have.

**Comment by derimagia** [comment]
How exactly did you want a plugin? Can you give me an example external plugin? Bash-it doesn't look like a package manager, more like a collection of aliases/scripts (Similar to oh-my-zsh).

[Antigen](https://github.com/zsh-users/antigen) and [Antibody](https://github.com/getantibody/antibody) are examples of Package Managers for ZSH (Along with others). I believe Antibody works with bash though. These let you install packages from github and you can use it for installing this package if you had ZSH. You can also use them to install oh-my-zsh scripts (See https://getantibody.github.io/compat/).

So I'm not exactly sure how we would add this. If bash-it has a package manager that I don't see I'd be fine with adding it.

**Comment by NGenetzky** [comment]
@derimagia , you make a good point. I am not sure if bash-it has support for external commands. I assumed `fzf` was a simlar case but it looks like installation of `fzf` is required before the plugin is useful.

Perhaps @nwinkler, could weigh in; I know he has contributed to that project because I use his theme :wink: .

**Comment by nwinkler** [comment]
There shouldn’t be anything special required for using git-open with Bash-it, right. Bash-it’s are more like additional scripts that use a tool like fzf in a smart way - installation if the tool itself is handled separately as you described.

Thanks for the plug for Bash-it, though - appreciate it!
