### ISSUE TITLE
Fish shell compatibility

### ISSUE THREAD

**Issue by MartinDelille** [paulirish/git-open#136]
I would like to use `git-open` with [Fish](https://fishshell.com/) but it doesn't worked.

I installed it with [fisher](https://github.com/jorgebucaran/fisher) plugin manager.

Do you think it could be possible to add `git-open` support to *Fish*?

**Comment by paulirish** [comment]
I use fish shell myself and have no problems. I install it via npm, so I guess the problem is the fisher package?

**Comment by MartinDelille** [comment]
I don't know what happen but I uninstalled it and reinstalled it: it works now.

**Comment by MartinDelille** [comment]
No it doesn't work. Thing we need to have a file like `conf.d/git-open.fish` that would add `git-open` to the path.

**Comment by MartinDelille** [comment]
I tried adding my local *git-open* clone to the path and it works!

I just have to figure out how to add it in a fish plugin.

**Comment by paulirish** [comment]
yup technically all that needs to happen is that `git-open` needs to be in the path. 

the `git` binary does the magic of mapping that to `git open`

**Comment by MartinDelille** [comment]
The `brew` do perfectly the job so I keep with that.

You can close the issue if you want because I won't provide fix for it in the end.
