### ISSUE TITLE
An option to just print and not open the link

### ISSUE THREAD

**Issue by AkarshSatija** [paulirish/git-open#137]
How about `git open --print`.

2 use cases:

1. I wish to use the URL in some other script
2. I have multiple browser windows open at any point in time, So I wish to open it in a particular window. `git open --print | pbcopy` would help a lot

**Comment by ffes** [comment]
In the README it says:

>You can run git-open in echo mode, which doesn't open your browser, but just prints the URL to stdout:
> ```
>env BROWSER='echo' ./git-open`
>```

I like the idea of an option like `--print` or `--debug`, but as always "Somebody has to do it"
