### ISSUE TITLE
WSL support?

### ISSUE THREAD

**Issue by roachsinai** [paulirish/git-open#138]
Could you please add support for bash on Windows?

**Comment by ffes** [comment]
There is :flushed:

I added it and use it every day on Ubuntu 18.04 in Windows 10 1809.

But since you asked this, you apparently have a problem. We need more details to see your problem

**Comment by roachsinai** [comment]
```
hwina ~ > pqs git-open
local/git-open-git r207.4eed00f-1
    Open a repo website in your browser. Development version.
hwina ~ >
```

I'm using arch installed by [ArchWSL](https://github.com/yuk7/ArchWSL)

```
hwina ~/c/G/dotfiles master > git remote -v
origin  git@github.com:roachsinai/dotfiles.git (fetch)
origin  git@github.com:roachsinai/dotfiles.git (push)
hwina ~/c/G/dotfiles master > git-open
hwina ~/c/G/dotfiles master >
```

There is no response of `git-open` or `git open`, no errors and didn't open web browser.

**Comment by roachsinai** [comment]
Sorry for this issue, as it works right now!!!

What's the difference is I just finished update to 19H1 release. I found the problem while updating win10.

**Comment by G-Rath** [comment]
I tried this on WSL and was pleasantly surprised to find it works (I was expecting it to fail complaining about being unable to open Chrome, or make a GUI call).

*However*, it seems to change the console to use Raster fonts - any ideas on what might be doing this?

http://puu.sh/E9t29/5daab5e7db.png

**Comment by ffes** [comment]
Please don't ask about **other**  issues in a closed issue.

This is a issue that only occurs in `cmd.exe` AFAIK. I think it is an upstream bug. With the new Terminal I don't see the problem.

**Comment by G-Rath** [comment]
> Please don't ask about other issues in a closed issue.

My apologies - I wanted to confirm *this was an issue* before opening a new issue, and wasting everyone's time.

I'll make an issue now.

**Comment by G-Rath** [comment]
I've made #152 to track this.
