### ISSUE TITLE
How to git open Bitbucket repo instead of /branch/master/?

### ISSUE THREAD

**Issue by zulhfreelancer** [paulirish/git-open#28]
When I typed `git open` inside Github project, it opens my Github remote repo page nicely. Example:
https://github.com/paulirish/git-open

But, when I typed `git open` inside Bitbucket project, it opens my Bitbucket remote repo like this:
https://bitbucket.org/[username]/[repo]/branch/master

How do I open it like this?
https://bitbucket.org/[username]/[repo]
(without `/branch/master/` part)

Note:
This Bitbucket project is private project.

**Comment by paulirish** [comment]
should be easy to fix in the source. give me a PR and i'll merge.

**Comment by zulhfreelancer** [comment]
Can you give me some hints how to start?

**Comment by allanino** [comment]
Hey @zulhfreelancer, you might want to take a look at this similar project which handle this case already: https://github.com/gerep/git-open. Also, it may give you some clues about how to solve the problem in this project, if you prefer.

**Comment by hotoo** [comment]
Maybe you want https://github.com/hotoo/gitopen
