### ISSUE TITLE
Repo cloned with SSH is not opening

### ISSUE THREAD

**Issue by oluckyman** [paulirish/git-open#29]
I have a private github repo with URL in SSH format:  
```bash
$ git config --get remote.origin.url
ssh://git@github.com/foo/bar.git
```
When I running `git open` in iTerm the Terminal app is opening:
<img width="655" alt="ss 2015-08-25 at 6 51 42 pm" src="https://cloud.githubusercontent.com/assets/642673/9473302/682d437c-4b5a-11e5-9ad7-b63f74ca8245.png">

**Comment by evoactivity** [comment]
I'm using a custom gitlab host (and a custom port) and this is exactly what happens when I run `git open`

**Comment by xasx** [comment]
@evoactivity I am seeing this as well - have you found a way around this? PR?

**Comment by paulirish** [comment]
this was fixed with this rewrite line: https://github.com/paulirish/git-open/pull/30/files

obv it was github specific. do you want to contribute a fix that works for gitlab?

**Comment by evoactivity** [comment]
@xasx I submitted a pull request that fixed this back in August, it might not fix your exact issue though https://github.com/paulirish/git-open/pull/51/files but it might point you in the direction for a fix you can submit.

**Comment by xasx** [comment]
I tried something that works for me :laughing: 

Please check/review whether it breaks something else.
