### ISSUE TITLE
Update the npm package

### ISSUE THREAD

**Issue by nwinkler** [paulirish/git-open#40]
Would it be possible to update the package published on npmjs.org? https://www.npmjs.com/package/git-open

The current release is over one year old...

**Comment by davidosomething** [comment]
@paulirish can you add me to npm package r/w access or owners list?

**Comment by paulirish** [comment]
David, added.

**Comment by davidosomething** [comment]
@nwinkler bumped to 1.1.0: https://www.npmjs.com/package/git-open

**Comment by nwinkler** [comment]
Awesome - thanks!
