### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by theoriginalbit** [paulirish/git-open#42]
I was testing this plugin with my repo and it opened the URL `https://github.com/theoriginalbit/repo//master` instead of `https://github.com/theoriginalbit/repo/tree/master` resulting in GitHub 404'ing.

**Comment by theoriginalbit** [comment]
*EDIT:* I just saw the note about the NPM repo being massively outdated. Updating it fixed GitHub, but _not_ GitHub Enterprise which can be hosted at any domain, i.e. `https://companydomain/org/repo.git` or `git@companydomain:org/repo.git`

**Comment by davidosomething** [comment]
open a PR adding GH enterprise support if you want and I'll review it, otherwise see #3

**Comment by davidosomething** [comment]
related #40
