### ISSUE TITLE
-Requirements?- OMZ Config

### ISSUE THREAD

**Issue by alock** [paulirish/git-open#43]
I am having trouble getting this to work with the `.oh-my-zsh` install instructions.  First question does this require hub to be installed?

```
$  git --version
git version 2.6.4 (Apple Git-63)
$ git open
git: 'open' is not a git command. See 'git --help'.

Did you mean one of these?
	clean
	clone
	notes
	prune
```

**Comment by davidosomething** [comment]
Hub is a separate project, it is not required for this.

Can you show us the files you've modified? (perhaps put your dotfiles up on GitHub)
We'll need to confirm that:

1. this file exists: `~/.oh-my-zsh/custom/plugins/git-open/git-open.plugin.zsh`
1. the `plugins=()` array in your `.zshrc` file contains the string `git-open`

OMZ 3rd-party plugin installation:
https://github.com/robbyrussell/oh-my-zsh/wiki/Customization#overriding-and-adding-plugins

If the OMZ setup is all fine, we'll proceed to debug the plugin itself

**Comment by unixorn** [comment]
One of my interns who still uses oh-my-zsh told me that he had problems with custom plugins with dashes in the names. I'm using zgen which doesn't have issues with that.

**Comment by alock** [comment]
Here is my file structure for custom plugins within `.oh-my-zsh` and this is what I have in the `.zshc` file `plugins=(gitfast docker git-open)`.

```
$ tree ~/.oh-my-zsh/custom/plugins
/Users/adam.lock/.oh-my-zsh/custom/plugins
├── example
│   └── example.plugin.zsh
├── git-it-on
│   ├── README.md
│   └── git-it-on.plugin.zsh
└── gitopen
    ├── README.md
    ├── git-open
    ├── git-open.plugin.zsh
    ├── markdownlint.json
    └── package.json

3 directories, 8 files
```

**Comment by davidosomething** [comment]
Hm can you try manually renaming `/Users/adam.lock/.oh-my-zsh/custom/plugins/gitopen/git-open.plugin.zsh` to `/Users/adam.lock/.oh-my-zsh/custom/plugins/gitopen/gitopen.plugin.zsh` (no dash)?

Looks like omz might want the plugin file to be without-dash if the name of the plugin in `plugins=()` doesn't have it (https://github.com/robbyrussell/oh-my-zsh/blob/master/oh-my-zsh.sh#L38-L43)

I'll update the filename here if that works

**Comment by unixorn** [comment]
ok, try renaming gitopen to git-open since your git-it-on plugin directory has dashes and is working.

**Comment by unixorn** [comment]
@davidosomething let's see if omz really chokes on the dashes - it looks like they have fixed that since his git-it-on plugin is working. If we rename the `.plugin.zsh` file it might cause issues with zgen and antigen if they're expecting the plugin file to be named after the repo.

**Comment by alock** [comment]
Thanks for the fast response guys.  It looks like both of the suggestions resolve the issue, and I thought I tested it with a dash in the dot file, but I guess I didn't.

I've been meaning to switch to `zgen` just too lazy right now.  Thanks again!

**Comment by alock** [comment]
Sorry guys looks like the dash in the `.zshrc` file only worked because OMZ was still referencing the file name change I did right before it.

**Comment by alock** [comment]
Looks like you already fixed it the directory name has to match as well.  Thanks!

**Comment by unixorn** [comment]
@alock - zgen will let you keep using the omz plugins you're used to and has much faster startup times for new terminal windows. Well worth the effort of switching :-)
