### ISSUE TITLE
git open current upstream

### ISSUE THREAD

**Issue by virtuald** [paulirish/git-open#65]
If I have multiple remotes, and I do a `git push -u other branchname`, I would expect 'git open' to open whatever the current remote is, as opposed to using origin.

**Comment by paulirish** [comment]
Yeah this seems completely reasonable. 

I don't work with this pattern much so I'd love your help here..  What's the most reliable technique you're seeing for getting the tracked remote?  (some [relevant SO answers](http://stackoverflow.com/questions/171550/find-out-which-remote-branch-a-local-branch-is-tracking) here)

**Comment by virtuald** [comment]
Well, some experimentation shows that `git for-each-ref --format='%(upstream:short)' $(git symbolic-ref -q HEAD)` seems to be pretty good. For a branch with no tracking information, it outputs nothing, and for a branch with tracking information, it outputs `remote/branch`.
