### ISSUE TITLE
Support for Gitlab?

### ISSUE THREAD

**Issue by montogeek** [paulirish/git-open#8]
Is there any plans to support Gitlab? Specially those repos that are self hosted.

**Comment by CauanCabral** [comment]
It's easy to add support for your Gitlab repo, but I think is much specific for global solution (without some type of setting)

I did that to use with my Gitlab server

```shell
# Github support
if grep -q github <<<$giturl; then
    giturl=${giturl/git\@github\.com\:/https://github.com/}
# Gitlab support
elif grep -q gitlab.domain <<<$giturl; then
    giturl=${giturl/git\@gitlab\.domain\.com\:/https://gitlab.domain.com/}
# bitbucket support
elif grep -q bitbucket <<<$giturl; then
    giturl=${giturl/git\@bitbucket\.org\:/https://bitbucket.org/}
fi
```

**Comment by paulirish** [comment]
@montogeek hook me up with a pull request and i'll merge it in a heartbeat.

**Comment by brunobatista** [comment]
+1

**Comment by simonweil** [comment]
:+1: 
I'd love bitbucket support!

**Comment by bbeardsley** [comment]
That's already there.

**Comment by paulirish** [comment]
@bbeardsley thanks for the hookup on gitlab

**Comment by montogeek** [comment]
thanks @bbeardsley

**Comment by simonweil** [comment]
True, I missed that!
Thanks :)

**Comment by paulirish** [comment]
Merged in @bbeardsley's work.  Test it out !

**Comment by montogeek** [comment]
Thanks!
